# commit to be tagged for the new release
commit = "HEAD"

project_name = "image-factory"
github_repo = "siderolabs/image-factory"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v1.0.0"
pre_release = false

[notes]

[make_deps]

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
