apiVersion: kuttl.dev/v1beta1
kind: TestSuite
metadata:
  name: image-factory-helm-chart
startKIND: false
namespace: image-factory-e2e
crdDir: ./_crds
manifestDirs:
  - ./_manifests
testDirs:
  - ./tests
timeout: 600
parallel: 1
commands:
  - command: kubectl kuttl version
  - command: helm version
