{{- if .Values.gatewayApi.pxe.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "image-factory.fullname" . }}
  namespace: {{ include "image-factory.namespace" . }}
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
    {{- with .Values.gatewayApi.pxe.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gatewayApi.pxe.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayApi.pxe.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gatewayApi.pxe.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "image-factory.fullname" $ }}
          port: {{ .Values.service.main.port }}
{{- end }}