{{- if not .Values.cacheSigningKey.existingSecret }}
{{- $key := .Values.cacheSigningKey.key  | required ".Values.cacheSigningKey.key is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-factory.fullname" . }}-cache-signing-key
  namespace: {{ include "image-factory.namespace" . }}
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
type: Opaque
stringData:
  cache-signing.key: |
    {{- $key | nindent 4 }}
{{- end }}
