{{- if not .Values.cacheSigningKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-factory.fullname" . }}-cache-signing-key
  namespace: {{ include "image-factory.namespace" . }}
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
type: Opaque
stringData:
  cache-signing.key: |
    {{- .Values.cacheSigningKey.key | nindent 4 }}
{{- end }}