{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-factory.fullname" . }}-metrics
  namespace: {{ include  "image-factory.namespace" . }}
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
    {{- with .Values.service.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.metrics.service.type }}
  {{- if and .Values.service.metrics.service.clusterIP (eq .Values.service.metrics.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.metrics.service.clusterIP }}
  {{- end }}
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.service.metrics.service.servicePort }}
    targetPort: metrics
  selector:
    {{- include "image-factory.selectorLabels" . | nindent 4 }}
{{- end }}

